@server_HostAddress = http://localhost:5173

GET {{server_HostAddress}}/api/savedBooks/
Accept: application/json
###
POST {{server_HostAddress}}/api/book/
Accept: application/json
Content-Type: application/json